services:
  gastracker:
    build: .
    restart: unless-stopped
    ports:
      - "5220:8080"
    volumes:
      - /var/docker/GasTracker/Data:/app/data
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Data Source=/app/data/gastracker.db
    env_file: /root/docker/gt_env.env
