<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\GasTracker.Data\GasTracker.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazorise" />
    <PackageReference Include="Blazorise.Bootstrap5" />
    <PackageReference Include="Blazorise.Charts" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>e70abd6d-ca5b-4e9e-9f71-ee2074e31b2d</UserSecretsId>
  </PropertyGroup>

</Project>
